import { useState, useRef, useEffect } from "react";
import Head from "next/head";
import { Form } from "@unform/web";
import { setCookie, parseCookies } from "nookies";
import { useRouter } from "next/router";

import { ToastContainer } from "react-toastify";
import { AiFillEye, AiFillEyeInvisible, AiOutlineUser } from "react-icons/ai";

import styles from "../styles/Home.module.scss";
import "react-toastify/dist/ReactToastify.css";
import { api } from "./api/hello";
import { Input } from "../components/InputComponent";

export default function Home() {
  const router = useRouter();
  const formRef = useRef();
  const [inputType, setInputType] = useState("password");
  function handleTypeInputText() {
    setInputType("text");
  }
  function handleTypeInputPassword() {
    setInputType("password");
  }

  async function handleSubmit(data, { reset }) {
    const response = await api.post("user/login", data);

    if (response.status === 200) {
      toast.success("Logado com sucesso");
      setCookie("quizz", data, {
        maxAge: 60 * 60 * 24, //one day
      });
      const cookie = parseCookies();
      const user = jwt_decode(cookie);

      if (user) {
        router.push("/quizz");
      }
    }
    if (response.status >= 400) {
      toast.error("Tivemos um erro verifque seu usuario ou senha");
    }
    reset();
  }

  return (
    <div className={styles.ContainerContent}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.ContainertForm}>
        <div className={styles.classNameTopSvgUSer}>
          <AiOutlineUser />
        </div>
        <h2>Login</h2>
        <main>
          <Form ref={formRef} onSubmit={handleSubmit}>
            <Input name="user.email" type="text" placeholder="email" required />
            <div>
              <Input
                name="user.password"
                type={inputType}
                placeholder="password"
                required
                minlength="4"
              />
              {inputType === "password" ? (
                <AiFillEye onClick={handleTypeInputText} />
              ) : (
                <AiFillEyeInvisible onClick={handleTypeInputPassword} />
              )}
            </div>
            <div>
              <button type="submit">Login</button>
            </div>
          </Form>
        </main>
      </div>
      <ToastContainer />
    </div>
  );
}
